### ISSUE TITLE
支持mac操作系统么？

### ISSUE THREAD

**Issue by 418926059** [jerrylizilong/autotest_platform#16]

**Comment by jerrylizilong** [comment]
> _No description provided._

只要可以运行python、selenium ，就可以支持的

**Comment by 418926059** [comment]
app/client.py 中 会判断platform.system，不是win的话会提示other system is not supported yet !

**Comment by jerrylizilong** [comment]
> app/client.py 中 会判断platform.system，不是win的话会提示other system is not supported yet !

因为我是在 Windows 下开发的，没试过 mac 里能不能运行。  你可以把这个判断条件改掉试一下：
if platform.system() == 'Windows':

改为   
if True：

**Comment by 418926059** [comment]
我试了一下 运行起来了  mac的判断语句是 if platform.system() == 'Darwin':   有时间我会试一下linux的
