### ISSUE TITLE
用例集问题

### ISSUE THREAD

**Issue by luomomimi** [jerrylizilong/autotest_platform#17]
1.关联用例后突然自动执行了用例（应该手动触发执行事件后在执行任务）
2.用例集执行android用例时，所有用例一同执行（应该执行完成一个后在执行另一个用例）

**Comment by jerrylizilong** [comment]
> 1.关联用例后突然自动执行了用例（应该手动触发执行事件后在执行任务）
> 2.用例集执行android用例时，所有用例一同执行（应该执行完成一个后在执行另一个用例）

第一个问题已修复，把默认状态改为 了- 1， 这样不会自动执行

第二个问题，用例设置是并行的（根据设备数量进行并发），这样才能保证运行效率
