### ISSUE TITLE
关键字驱动这里有些不理解

### ISSUE THREAD

**Issue by 418926059** [jerrylizilong/autotest_platform#18]
comed = buildCase.buildCase().build_case(keyword, steps[1]) 这里是组装可执行语句，然后用exec(comed） 来执行语句，但是我有些看不懂这个语句是怎么执行的，有相关文档的地址么？谢谢

**Comment by jerrylizilong** [comment]
> comed = buildCase.buildCase().build_case(keyword, steps[1]) 这里是组装可执行语句，然后用exec(comed） 来执行语句，但是我有些看不懂这个语句是怎么执行的，有相关文档的地址么？谢谢

可以看这篇帖子 https://testerhome.com/articles/17671
