### ISSUE TITLE
Android用例集问题

### ISSUE THREAD

**Issue by luomomimi** [jerrylizilong/autotest_platform#19]
1、在用例集界面点击执行，用例实际不会执行，只有用例集状态会变为准备执行
2、点击执行详情，执行状态为cases[i][3]
3、例如一个Android用例集有三个用例，设备列表有2个手机，点击执行，所有Android用例在同一部手机执行，不会在所有手机上分别执行某个用例

**Comment by jerrylizilong** [comment]
> 1、在用例集界面点击执行，用例实际不会执行，只有用例集状态会变为准备执行
> 2、点击执行详情，执行状态为cases[i][3]
> 3、例如一个Android用例集有三个用例，设备列表有2个手机，点击执行，所有Android用例在同一部手机执行，不会在所有手机上分别执行某个用例

问题1、3 ，设计如此
问题2 已修复
