### ISSUE TITLE
如果你把selenium的api在web进行封装，那就没什么价值

### ISSUE THREAD

**Issue by t2437153** [jerrylizilong/autotest_platform#2]
如果你把selenium的api在web进行封装，那就没什么价值

**Comment by jerrylizilong** [comment]
你的意义就是到处给人留言没价值吗？

**Comment by t2437153** [comment]
rubbish people

**Comment by jerrylizilong** [comment]
> > 你的意义就是到处给人留言没价值吗？
> 
> 自己做的垃圾还不接受批评，你看有人给你留言吗垃圾？

看你自己的活动记录，除了给别人的project 评论“没意义”  之外还做了什么？
