### ISSUE TITLE
在初次运行时，无法运行，点击重跑，才运行成功。

### ISSUE THREAD

**Issue by abc996770151** [jerrylizilong/autotest_platform#20]
web,UI测试，Chrome
1.编辑完用例或用例集，点击执行，
![1](https://user-images.githubusercontent.com/20945295/58071813-5cb09080-7bd0-11e9-969e-d2f6e2d3e573.png)
查看详情，没有执行，且查看日志没有任何更新
![2](https://user-images.githubusercontent.com/20945295/58071822-65a16200-7bd0-11e9-96c0-b5c3cfe60675.png)
点击重跑用例，才进入执行状态。

**Comment by jerrylizilong** [comment]
> web,UI测试，Chrome
> 1.编辑完用例或用例集，点击执行，
> ![1](https://user-images.githubusercontent.com/20945295/58071813-5cb09080-7bd0-11e9-969e-d2f6e2d3e573.png)
> 查看详情，没有执行，且查看日志没有任何更新
> ![2](https://user-images.githubusercontent.com/20945295/58071822-65a16200-7bd0-11e9-96c0-b5c3cfe60675.png)
> 点击重跑用例，才进入执行状态。

已修复
