### ISSUE TITLE
Android用例集问题（续）

### ISSUE THREAD

**Issue by luomomimi** [jerrylizilong/autotest_platform#23]
例如一个Android用例集有三个用例，设备列表有2个手机，点击执行，所有Android用例在同一部手机同时执行，不会在所有手机上分别执行某个用例
形象来说，在手机A上，用例a、b、c，8:00这个时刻同时执行；同一个手机APP在同一时间执行了三个用例，这会导致执行的所有用例都失败。
网页由于可以多开浏览器所以无问题

**Comment by jerrylizilong** [comment]
暂时没空确认和排查
