### ISSUE TITLE
执行用例失败，显示无法执行

### ISSUE THREAD

**Issue by sky1984** [jerrylizilong/autotest_platform#26]
![image](https://user-images.githubusercontent.com/13880255/63674160-835a1500-c818-11e9-8ec3-ee2e7a133d6f.png)
![image](https://user-images.githubusercontent.com/13880255/63674176-894ff600-c818-11e9-8bdd-adc7a75040d1.png)

**Comment by hflyf123** [comment]
遇到了同样的问题，不知道如何排查？
