### ISSUE TITLE
vmware搭建在centos下，手机连接到该虚拟机时，android画面不显示

### ISSUE THREAD

**Issue by sonicno1** [jerrylizilong/autotest_platform#28]
vmware搭建在centos下，手机连接到该虚拟机下adb模式连接成功（windows显示正常），android画面不显示

**Comment by jerrylizilong** [comment]
没接触过你的这种搭建方式，我这个平台用的是atx Server

**Comment by sonicno1** [comment]
那就是说atx server仅支持windows?
