### ISSUE TITLE
能否增加基于浏览器的插件，实现录制测试用例的功能

### ISSUE THREAD

**Issue by yanjingtu** [jerrylizilong/autotest_platform#29]
如题。目前看，这个项目是很不错的一个自动化测试平台，但是对于测试人员水平不高，或界面经常变动，或测试人手不足的情况下，编写大量测试用例还是比较麻烦的。
看到网上有一个基于浏览器扩展的实现，https://docs.seleniumhq.org/selenium-ide/
可以直接录制操作步骤，导出成selenium脚本之类。
这种基本不需要测试人员有较强的html等理解能力，傻瓜化操作。
不知道是否容易实现。

**Comment by jerrylizilong** [comment]
> 如题。目前看，这个项目是很不错的一个自动化测试平台，但是对于测试人员水平不高，或界面经常变动，或测试人手不足的情况下，编写大量测试用例还是比较麻烦的。
> 看到网上有一个基于浏览器扩展的实现，https://docs.seleniumhq.org/selenium-ide/
> 可以直接录制操作步骤，导出成selenium脚本之类。
> 这种基本不需要测试人员有较强的html等理解能力，傻瓜化操作。
> 不知道是否容易实现。

1. selenium ide是很早就有了，但是用的人很少，而且好像已经不维护了。你可以去了解一下录制出来脚本的稳定性，维护成本不低，特别你说的大量用例，维护起来会是很大一个坑
2. 现在的框架只是在浏览器里查看元素编写用例，学习成本已经很低了
3. 如果你还是倾向录制，可以考虑用录制出来的代码放到pytest 或者JAVA 的testng 里面简单修改和维护，那些框架有很好的报表支持

**Comment by yanjingtu** [comment]
感谢说明😊

在 2019-11-16 23:16:19，"Jerry Li" <notifications@github.com> 写道：


如题。目前看，这个项目是很不错的一个自动化测试平台，但是对于测试人员水平不高，或界面经常变动，或测试人手不足的情况下，编写大量测试用例还是比较麻烦的。
看到网上有一个基于浏览器扩展的实现，https://docs.seleniumhq.org/selenium-ide/
可以直接录制操作步骤，导出成selenium脚本之类。
这种基本不需要测试人员有较强的html等理解能力，傻瓜化操作。
不知道是否容易实现。

selenium ide是很早就有了，但是用的人很少，而且好像已经不维护了。你可以去了解一下录制出来脚本的稳定性，维护成本不低，特别你说的大量用例，维护起来会是很大一个坑
现在的框架只是在浏览器里查看元素编写用例，学习成本已经很低了
如果你还是倾向录制，可以考虑用录制出来的代码放到pytest 或者JAVA 的testng 里面简单修改和维护，那些框架有很好的报表支持
