### ISSUE TITLE
README中启动hub,少了个单词 b 

### ISSUE THREAD

**Issue by yuyang199226** [jerrylizilong/autotest_platform#30]
`docker run -d -p 4444:4444 --net grid --name selenium-hub selenium/hu`
应该是
`docker run -d -p 4444:4444 --net grid --name selenium-hub selenium/hub`

**Comment by jerrylizilong** [comment]
> `docker run -d -p 4444:4444 --net grid --name selenium-hub selenium/hu`
> 应该是
> `docker run -d -p 4444:4444 --net grid --name selenium-hub selenium/hub`

谢谢，已加上
