### ISSUE TITLE
能不能麻烦宁看下，这里没有执行成功。

### ISSUE THREAD

**Issue by No-sleeping** [jerrylizilong/autotest_platform#37]
这里的服务端已经开启了，也检测到 selenium server，节点管理也是开启状态。
![image](https://user-images.githubusercontent.com/29038574/93729365-bd9e0d80-fbf6-11ea-9837-a5332d89e4ae.png)
但是这里还是【待执行】的状态。，查看截图也没有。
![image](https://user-images.githubusercontent.com/29038574/93729375-ca226600-fbf6-11ea-850f-63686aeb2cc4.png)
能麻烦看下是为什么

**Comment by No-sleeping** [comment]
0

**Comment by jerrylizilong** [comment]
你还要启动你的selenium client端才能真正开始执行对应的用例

**Comment by No-sleeping** [comment]
> 你还要启动你的selenium client端才能真正开始执行对应的用例

好的我启动了，谢谢了

**Comment by jeffliu2019** [comment]
谁呀，如何知道我！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jerrylizilong/autotest_platform"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月22日(星期二) 下午2:27
收件人:&nbsp;"jerrylizilong/autotest_platform"<autotest_platform@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [jerrylizilong/autotest_platform] 能不能麻烦宁看下，这里没有执行成功。 (#37)





  
你还要启动你的selenium client端才能真正开始执行对应的用例
  
好的我启动了，谢谢了

**Comment by No-sleeping** [comment]
> 谁呀，如何知道我！！！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jerrylizilong/autotest_platform" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月22日(星期二) 下午2:27 收件人:&nbsp;"jerrylizilong/autotest_platform"<autotest_platform@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [jerrylizilong/autotest_platform] 能不能麻烦宁看下，这里没有执行成功。 (#37) 你还要启动你的selenium client端才能真正开始执行对应的用例 好的我启动了，谢谢了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

？？？

**Comment by jerrylizilong** [comment]
> > 你还要启动你的selenium client端才能真正开始执行对应的用例
> 
> 好的我启动了，谢谢了

问题解决了吗？

**Comment by No-sleeping** [comment]
> > > 你还要启动你的selenium client端才能真正开始执行对应的用例
> > 
> > 
> > 好的我启动了，谢谢了
> 
> 问题解决了吗？

解决了，我现在看下自定义关键字的地方。

**Comment by jerrylizilong** [comment]
> 谁呀，如何知道我！！！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jerrylizilong/autotest_platform" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月22日(星期二) 下午2:27 收件人:&nbsp;"jerrylizilong/autotest_platform"<autotest_platform@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [jerrylizilong/autotest_platform] 能不能麻烦宁看下，这里没有执行成功。 (#37) 你还要启动你的selenium client端才能真正开始执行对应的用例 好的我启动了，谢谢了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可能你watch了这个project，邮件自动抄送给你了

**Comment by jerrylizilong** [comment]
not an issue
