### ISSUE TITLE
Whether image can be inserted in kityminder or not?

### ISSUE THREAD

**Issue by catmemo** [jerrylizilong/autotest_platform#41]
Whether image can be inserted in kityminder or not?

**Comment by jerrylizilong** [comment]
sorry, I am not awere of this

**Comment by catmemo** [comment]
> sorry, I am not awere of this

Sorry, I did not make myself clear.
You have integrated the function of kityminder-editor in the program.
And kityminder-editor is able to upload images to minder map.
So whether the integrated kityminder-editor in your program can upload images or not?
Thank you very much!
