### ISSUE TITLE
我的节点端口是启动的状态，但是执行说我端口没启动

### ISSUE THREAD

**Issue by Cintaw** [jerrylizilong/autotest_platform#48]
![image](https://user-images.githubusercontent.com/97600026/149129609-00094e47-f01f-4d5b-86a9-c0d3499a012d.png)
![image](https://user-images.githubusercontent.com/97600026/149129757-1d785da6-3d8e-48b5-9d23-2acb2964fe6d.png)
我的节点端口是启动的状态，但是执行说我端口没启动，执行用例不成功

**Comment by jerrylizilong** [comment]
> ![image](https://user-images.githubusercontent.com/97600026/149129609-00094e47-f01f-4d5b-86a9-c0d3499a012d.png) ![image](https://user-images.githubusercontent.com/97600026/149129757-1d785da6-3d8e-48b5-9d23-2acb2964fe6d.png) 我的节点端口是启动的状态，但是执行说我端口没启动，执行用例不成功

请确定一下对应的端口是否是正常可访问的，比如打开
http://localhost:4444/grid/console  检查一下状态

**Comment by jerrylizilong** [comment]
@Cintaw 你的两个docker 服务直接的网络通信是否正常呢？

**Comment by Cintaw** [comment]
> @Cintaw 你的两个docker 服务直接的网络通信是否正常呢？
网络应该是没有问题的，直接copy的代码，我发现一个现象，我重启docker以后，容器就退出了
![image](https://user-images.githubusercontent.com/97600026/149441854-9df7d8b4-e352-486f-b82d-891c877978a4.png)
